Storvsc backports
LIS/lis-next pull request #742
Opened 2022-05-10 21:19 UTC by sharsonia

2022-05-10 21:21 UTC, sharsonia commented
@johnsongeorge-w

2022-05-10 22:46 UTC, johnsongeorge-w commented
1. Limit the commit messages to 80 characters. Move the Backporting info to next line.
2. Specify the upstream link used for backporting. Refer the previous backports.

2022-05-10 23:09 UTC, johnsongeorge-w requested changes

2022-05-13 19:50 UTC, johnsongeorge-w commented on hv-rhel6.x/hv/storvsc_drv.c
>  		if (ret) {
Remove curly braces to match the backport

2022-05-13 23:44 UTC, johnsongeorge-w commented on hv-rhel6.x/hv/storvsc_drv.c
> +	struct Scsi_Host *host
This code will not compile.

2022-05-13 23:44 UTC, johnsongeorge-w commented on hv-rhel6.x/hv/storvsc_drv.c
> +			alloc_ordered_workqueue("storvsc_error_wq_%d",
In 2.6.32-754.el6.x86_64, alloc_ordered_workqueue takes only 2 args.
/usr/src/kernels/2.6.32-754.el6.x86_64/include/linux/workqueue.h:#define alloc_ordered_workqueue(name, flags) create_singlethread_workqueue(name)

2022-05-13 23:44 UTC, johnsongeorge-w commented on hv-rhel6.x/hv/storvsc_drv.c
> +			.roles = FC_PORT_ROLE_FCP_DUMMY_INITIATOR,
FC_PORT_ROLE_FCP_DUMMY_INITIATOR is not defined.

2022-05-17 02:04 UTC, johnsongeorge-w approved these changes

2022-05-17 02:05 UTC, merged